import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/client/LayoutWrapper";
import StoreProvider from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "FilmoraX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <StoreProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
